### ISSUE TITLE
Use gender-neutral language (cioè perifrasi ardite perché in italiano non c'è molta scelta)

### ISSUE THREAD

**Issue by lvps** [WEEE-Open/WEEEhire#11]
E.g. here: https://github.com/WEEE-Open/WEEEhire/blob/3e523f7b99704c7fcf67e922d47e2f870aa656fd/weeehire/templates/soviet.xhtml#L6
"Sei sicuro" should be "Sei sicuro/a" or some _perifrasi ardita_. Or change the base language to English and leave the admin panel untranslated, to solve at least part of the problem...

**Comment by Hyd3L** [comment]
Do we have female admins? lol

**Comment by lvps** [comment]
No, but do we want be that way forever?

**Comment by Hyd3L** [comment]
Ok... let's convert every "Sei sicuro?" with "Continuare?" asd

**Comment by lvps** [comment]
There's also a "caro utonto" (which should be changed to something more professional regardless, obviously):
https://github.com/WEEE-Open/WEEEhire/blob/1dbd8f178917fbc1d614e80ef8cc177646a06133/weeehire/controllers/form.py#L44

And maybe this but I think it's acceptable as it stands, too:
https://github.com/WEEE-Open/WEEEhire/blob/1dbd8f178917fbc1d614e80ef8cc177646a06133/weeehire/controllers/form.py#L132

**Comment by Hyd3L** [comment]
Maybe we should find some time together irl and decide ALL the end-user messages
