### ISSUE TITLE
Sending "approved" email should be optional or manual or customizable

### ISSUE THREAD

**Issue by lvps** [WEEE-Open/WEEEhire#29]
Instead of mandatory and automatic and not customizable.

We usually send a personalized email like "You seem a good candidate, write me on Telegram `@...`, please actually join us, please please please" (asd).

So any of these should be better:

* Add a checkbox "send confirmation email?"
* Add a separate "send approval email" button
* Allow admins to customize text before sending (but a non-automated email from a generic address doesn't look very professional)
* Don't send anything at all (very simple)

**Comment by Hyd3L** [comment]
I'd do like this: "Pubblica Risultati" publishes the decided results and nothing more. after the results are published, for each published result a "Contact" button will appear, and redirect the admin to a page that contains a textarea where you can write the email and that email will be sent to the direct interested asd and the textarea contains a made-with-stampino editable message.
