### ISSUE TITLE
Assign candidates to someone

### ISSUE THREAD

**Issue by lvps** [WEEE-Open/WEEEhire#30]
Allow assigning an approved candidate to some admin or "recruiter" or random WEEEino, so we know who contacted who.

Also useful for automated emails (if we send them, depends on #29): they could contain "Your request was approved blah blah blah please contact Some One at `@someone` on Telegram to talk more in detail" or something similar.

**Comment by Hyd3L** [comment]
I think the best thing to solve this is by adding a _recruiter_ column in the _users_ table.
