### ISSUE TITLE
Should we advise the scartati?

### ISSUE THREAD

**Issue by Hyd3L** [WEEE-Open/WEEEhire#40]
by removing the automatic email sending feature, we also deleted the automatic email for the scartati contestants. Should we re-enable it or it's better to leave them the pleasure to refresh the page like forsennati until they discover that we scarted them? asd

**Comment by lvps** [comment]
Can you add the "contact" button for them, too? Just with a different email template.

**Comment by Hyd3L** [comment]
As far as I remember, the last year nobody cared about them, so... why? Useless effort asd

**Comment by lvps** [comment]
Well, ok, but part of the reasons we decided to make our own software was to automate that bit

**Comment by Hyd3L** [comment]
Ok so, let's re-enable the "Ciawa! Sei stato scartato" email? asd

**Comment by lvps** [comment]
I have no opinion on this really: the status page should be enough even though it's a quite uncommon approach (when applying to companies, that is), but you should ask teh soviet:tm:
