### ISSUE TITLE
Move recruiters to database

### ISSUE THREAD

**Issue by lvps** [WEEE-Open/WEEEhire#41]
And add a page to at least view them. And add/edit/delete them, if possible (but then, what happens if an assigned recruiter is deleted?)

**Comment by lvps** [comment]
Yeah, leaving telegram usernames in a publicly visible file on the internet will have aaaaaaaabsolutely no downsides. We also need to add an "email" column for the "Reply-to" header, do you want to put your email address there in plaintext? And what if you decide to change your telegram username again? Do you do a new deployment each time?

**Comment by Hyd3L** [comment]
.....
porcodio you're right asd
