### ISSUE TITLE
Add rejection reason

### ISSUE THREAD

**Issue by lvps** [WEEE-Open/WEEEhire#52]
So we can write stuff like "We have no more space available this semester/year, but try again next semester/year!" (only to some people, that's the point). It should be an optional field, obviously.

**Comment by Hyd3L** [comment]
Should we do this via e-mail or directly in the `form-status.xhtml`?
In the first case we could just contact them via e-mail cause we have the matricola,
in the second case we have to modify the `tg_user` table and add the reason out there.

But.... do we really need to add this feature? asd
I mean, if someone will be so upset for not accepting his WONDERFUL request,
he will just contact us via email and ask for further details asd

**Comment by lvps** [comment]
I think `form-status.xhtml` should be enough.

My reasoning is: "If we get so many highly qualified candidates and we can't possibly fit all of them in lab, I want the ones that arrived late to try again in future rather than giving up".

We could always contact them ourselves after a year, but lots of things may have changed (no more free time, went to another university with the Erasmus programme, people that si danno all'ippica, etc...) and... well, that's what company in theory do in similar cases, in practice they never contact anyone...

Still, sometimes adding a reason looks better than a plain "Rejected, go away". Companies rarely ever give any explanation, but telling candidates where they should improve is usually considered acceptable, so this might serve a similar purpose in some cases.

**Comment by Hyd3L** [comment]
We're not goddamn teachers, I appreciate your humanity and your willing in share knowledge, giveaway tips and so on, I'd love to do this too...
But it looks extremely time consuming to apply such approach to EACH request we will get,
so... in my opinion, since the special people we will reject will be likely 1 or 2 cats, we have
their matricola, we could just send em an e-mail and it's done...
IMO this is not the highest priority ATM

**Comment by lvps** [comment]
I agree this is low priority, we could indeed release a working version of the software without this feature.

Moreover, as I stated multiple times, this applies **only to some people**: the goal was to give a reason to those "1 or 2 cats" instead of everyone...

**Comment by Hyd3L** [comment]
Yea sure, but the coding effort could be easily replaced with copy-paste a matricola and write an e-mail, if you agree asd
So we avoid the risk of loosing time implementing a feature that we will use once a year asd

**Comment by lvps** [comment]
Well, K, let's copy and paste for now.
