### ISSUE TITLE
Add Reply-To to all emails

### ISSUE THREAD

**Issue by lvps** [WEEE-Open/WEEEhire#53]
And don't store that address in the source code (development.ini/production.ini/deployment.ini is fine, obviously)

**Comment by Hyd3L** [comment]
Yea I had to retype it in the source code cause I had some troubles with environment variables in production (IDKW)

What do you exactly mean with this issue btw? asd

**Comment by lvps** [comment]
Emails are sent like this (with the address in plain text in code, nice... asd):

```
message = Message(subject="Reclutamento WEEE Open",
                          sender="weeeopen@some-russian-provider.ru",
                          recipients=[user.email_address],
                          body=("""Ciao!
                          ...
```

these should also contain a "reply-to" field with our "real" address, so people can reply to that. Email clients will use it automatically. Because people *will* reply. To ask "when will my candidatura be visionata da qualcuno tramite gli occhi?".

Actually, we have three alternatives:

* Let them reply to that address nobody looks at (and add a "Do not reply to this email" line which nobody will read)
* Add "Reply-To: weeeopen@our-real-address.it" (and don't place this one in the source code), we can still decide if they're legitimate questions that need an answer or not
* Add a "For any questions, contact us at weeeopen@our-real-address.it" (again, not in the source code), but some people would still reply to the email itself to the wrong address

We should still seriously consider https://sendgrid.com/ or similar services, anyways...

**Comment by Hyd3L** [comment]
Actually the proper way to fix this problem is tossing up a goddamn SMTP server and create a no-reply AT WEEE Open d0t IT email address asd

That way... we would look more professional and in case of someone trying to reply to that address we could literally ban him forever for not being able to understand the meaning of "no-reply" asd

**Comment by lvps** [comment]
That would be the best way to handle this issue, sure, but requires a lot of effort to set up. A lot. Really a lot. We can't possibly do it before releasing WEEEhire 1.0, so we need an alternative that doesn't act like a black hole.

I mean, weeeopen@some-russian-provider.ru looks like a legitimate address, but acts as a black hole. no-reply looks like a black hole and acts like a black hole, which is way different to me...

**Comment by Hyd3L** [comment]
I'll try to configure an SMTP server like OpenSMTP or try to do some workarounds with `sendmail`...
