### ISSUE TITLE
Don't use magic user with ID=1 for configuration variables

### ISSUE THREAD

**Issue by lvps** [WEEE-Open/WEEEhire#57]
Sender address for automated emails is currently stored in user 1 entry, see e.g. https://github.com/WEEE-Open/WEEEhire/commit/81cd2a7c765fd90032e3dc12b06c7b2221b9a37f

Moving that address to a less magic (more boring?) place would be better: an "options" database table, somewhere in developement.ini/production.ini if it allows custom variables, etc... (Environment variables didn't work)

**Comment by Hyd3L** [comment]
if I manage to find out how to gather this information from the `production.ini` it would be wonderful.
if I can't I'll create an options table.... to store just ONE COLUMN and ONE ROW asd
