### ISSUE TITLE
Send an email to us when someone fills the form

### ISSUE THREAD

**Issue by lvps** [WEEE-Open/WEEEhire#59]
Maybe allow enabling and disabling this feature or we'll receive 100 emails per day in the periodi più concitati del reclutamento, but it would be useful to avoid checking the admin panel every other day.

**Comment by Hyd3L** [comment]
I already thought about this but...
do you really want your email to be filled by 9685943 notification emails? asd

**Comment by lvps** [comment]
If by "9685943" you mean "1 every two months when we aren't actively recruiting" and it allows me not to constantly check the admin panel, yeah. asd
