### ISSUE TITLE
Add a button to easily toggle notifications.

### ISSUE THREAD

**Issue by Hyd3L** [WEEE-Open/WEEEhire#63]
It would be nice to have a comfortable button to enable / disable notification emails for recruiters when someone applies.

**Comment by lvps** [comment]
Already mentioned in #59 but yeah, that would be nice. Another row in the "preferences" table seems the easiest way, what do you think(pad (læl))?

**Comment by Hyd3L** [comment]
You mean [THIS](https://github.com/WEEE-Open/WEEEhire/commit/18fc3a8c589b2ce53d097856cc0c42efd2e88eea#diff-72c70299a3276c012cac91b5ee302afb) row in the _options_ table? asd
