### ISSUE TITLE
Ask for Telegram username (optional)?

### ISSUE THREAD

**Issue by lvps** [WEEE-Open/WEEEhire#7]
May be useful to skip the "We've selected you... now let's talk on Telegram" email

**Comment by lvps** [comment]
Contacting people directly on a medium that doesn't randomly mark messages as spam and deliver them to /dev/null seemed a good idea, but it's not that important, really...

Consider that any data on a person we won't select is "useless" and "fills" the database, too.

**Comment by Hyd3L** [comment]
In fact... so... closed asd
