### ISSUE TITLE
Add "start time" and "end time" to form submission

### ISSUE THREAD

**Issue by lvps** [WEEE-Open/WEEEhire#72]
Example of implementation:

* Add a `<input type="hidden" name="start" value="[Current date and time when form page is rendered]">` tag to the form. Users that know the existence of the *Inspect element* function can change that but nobody cares
* Store it in the database when form is submit, together with current time ("end time")
* Add those to the exported JSON
* Mention this data in the privacy policy

**Low priority** since it requires a database schema change and it's mostly a curiosity, maybe we can do it next year.

Would it change how we evaluate candidates? Maybe, maybe not.
Can't we already gauge how long it took from the length of the motivational letter? Yes but there may be some interesting exceptions.
Will the data be accurate? Sometimes, sometimes not, e.g. people opening the form, doing something else and coming back after an hour.
Do we really need this? No, but most data is always nice to have.

**Comment by Hyd3L** [comment]
IMHO... we should collect just the minimum necessary data...
The typing speed of a dude is not actually necessary and could potentially lead to anti-GDPR and non-free privacy practices...
I won't implement a feature that rapes the privacy of our users in this way.
No thanks asd

**Comment by lvps** [comment]
Breaking news: we already have this data. Twice. There's a duplicate column that shouldn't have existed in the first place. Stallman would surely be disappointed. asd
