### ISSUE TITLE
Add "notes" to each candidate in soviet

### ISSUE THREAD

**Issue by lvps** [WEEE-Open/WEEEhire#73]
Add an editable "notes" textbox in `soviet-read.xhtml`, so we can add stuff like "Ask for details on X during interview" or "Rejected because X, Y and Z".
Visible to admins only, obviously.

**Comment by Hyd3L** [comment]
Can be solved by adding an additional table and then join on `tg_user.user_id`

**Comment by lvps** [comment]
Sure, but that would still require modifications to the production
database, so there's not a lot of difference from the "joinless" version
